package org.hardcoders.socialapp.model;
// Generated Dec 1, 2012 6:03:02 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name="province"
    ,catalog="socialapp"
)
public class Province  implements java.io.Serializable {


     private double id;
     private Double cityId;
     private String name;

    public Province() {
    }

	
    public Province(double id) {
        this.id = id;
    }
    public Province(double id, Double cityId, String name) {
       this.id = id;
       this.cityId = cityId;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, precision=22, scale=0)
    public double getId() {
        return this.id;
    }
    
    public void setId(double id) {
        this.id = id;
    }
    
    @Column(name="cityId", precision=22, scale=0)
    public Double getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Double cityId) {
        this.cityId = cityId;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


