package org.hardcoders.socialapp.model;
// Generated Dec 8, 2012 12:21:54 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="socialapp"
)
public class User  implements java.io.Serializable {


     private Long id;
     private String fullname;
     private String email;
     private String password;
     private String mobile;
     private String tweeter;
     private Boolean sendByEmail;
     private Boolean sendByMobile;
     private Boolean sendByTweeter;
     private String username;
     private String authentication;

    public User() {
    }

    public User(String fullname, String email, String password, String mobile, String tweeter, Boolean sendByEmail, Boolean sendByMobile, Boolean sendByTweeter, String username, String authentication) {
       this.fullname = fullname;
       this.email = email;
       this.password = password;
       this.mobile = mobile;
       this.tweeter = tweeter;
       this.sendByEmail = sendByEmail;
       this.sendByMobile = sendByMobile;
       this.sendByTweeter = sendByTweeter;
       this.username = username;
       this.authentication = authentication;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="fullname")
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="mobile")
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    @Column(name="tweeter")
    public String getTweeter() {
        return this.tweeter;
    }
    
    public void setTweeter(String tweeter) {
        this.tweeter = tweeter;
    }
    
    @Column(name="sendByEmail")
    public Boolean getSendByEmail() {
        return this.sendByEmail;
    }
    
    public void setSendByEmail(Boolean sendByEmail) {
        this.sendByEmail = sendByEmail;
    }
    
    @Column(name="sendByMobile")
    public Boolean getSendByMobile() {
        return this.sendByMobile;
    }
    
    public void setSendByMobile(Boolean sendByMobile) {
        this.sendByMobile = sendByMobile;
    }
    
    @Column(name="sendByTweeter")
    public Boolean getSendByTweeter() {
        return this.sendByTweeter;
    }
    
    public void setSendByTweeter(Boolean sendByTweeter) {
        this.sendByTweeter = sendByTweeter;
    }
    
    @Column(name="username", length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="authentication", length=20)
    public String getAuthentication() {
        return this.authentication;
    }
    
    public void setAuthentication(String authentication) {
        this.authentication = authentication;
    }




}


