package org.hardcoders.socialapp.model;
// Generated Dec 2, 2012 1:31:00 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userroute generated by hbm2java
 */
@Entity
@Table(name="userroute"
    ,catalog="socialapp"
)
public class Userroute  implements java.io.Serializable {


     private Long id;
     private Long userId;
     private Long p1;
     private Long p2;
     private Long p3;
     private Long p4;
     private Long p5;
     private Long p6;
     private Long p7;

    public Userroute() {
    }

    public Userroute(Long userId, Long p1, Long p2, Long p3, Long p4, Long p5, Long p6, Long p7) {
       this.userId = userId;
       this.p1 = p1;
       this.p2 = p2;
       this.p3 = p3;
       this.p4 = p4;
       this.p5 = p5;
       this.p6 = p6;
       this.p7 = p7;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="userId")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="p1")
    public Long getP1() {
        return this.p1;
    }
    
    public void setP1(Long p1) {
        this.p1 = p1;
    }
    
    @Column(name="p2")
    public Long getP2() {
        return this.p2;
    }
    
    public void setP2(Long p2) {
        this.p2 = p2;
    }
    
    @Column(name="p3")
    public Long getP3() {
        return this.p3;
    }
    
    public void setP3(Long p3) {
        this.p3 = p3;
    }
    
    @Column(name="p4")
    public Long getP4() {
        return this.p4;
    }
    
    public void setP4(Long p4) {
        this.p4 = p4;
    }
    
    @Column(name="p5")
    public Long getP5() {
        return this.p5;
    }
    
    public void setP5(Long p5) {
        this.p5 = p5;
    }
    
    @Column(name="p6")
    public Long getP6() {
        return this.p6;
    }
    
    public void setP6(Long p6) {
        this.p6 = p6;
    }
    
    @Column(name="p7")
    public Long getP7() {
        return this.p7;
    }
    
    public void setP7(Long p7) {
        this.p7 = p7;
    }




}


