package org.hardcoders.socialapp.model;
// Generated Dec 8, 2012 12:21:54 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Userroute generated by hbm2java
 */
@Entity
@Table(name="userroute"
    ,catalog="socialapp"
)
public class Userroute  implements java.io.Serializable {


     private Long id;
     private Long userId;
     private Long p1;
     private Long p2;
     private String alertType;
     private String googleRoute;

    public Userroute() {
    }

    public Userroute(Long userId, Long p1, Long p2, String alertType, String googleRoute) {
       this.userId = userId;
       this.p1 = p1;
       this.p2 = p2;
       this.alertType = alertType;
       this.googleRoute = googleRoute;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="userId")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="p1")
    public Long getP1() {
        return this.p1;
    }
    
    public void setP1(Long p1) {
        this.p1 = p1;
    }
    
    @Column(name="p2")
    public Long getP2() {
        return this.p2;
    }
    
    public void setP2(Long p2) {
        this.p2 = p2;
    }
    
    @Column(name="alertType", length=20)
    public String getAlertType() {
        return this.alertType;
    }
    
    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }
    
    @Column(name="googleRoute", length=10000)
    public String getGoogleRoute() {
        return this.googleRoute;
    }
    
    public void setGoogleRoute(String googleRoute) {
        this.googleRoute = googleRoute;
    }




}


